/**
 * Lista de todos os ícones "material-symbols-outlined" usados no site.
 *
 * A API do Google Fonts para Material Symbols permite pedir só os ícones
 * usados via `icon_names`, em vez da fonte inteira (que tem milhares de
 * glifos e pesa ~1MB por variação de peso). Isso reduz o payload de ~7MB
 * para ~80KB.
 *
 * Se adicionar um ícone novo em qualquer página, inclua o nome aqui
 * (o mesmo texto usado dentro do <span className="material-symbols-outlined">).
 */
const USED_ICONS = [
  "account_tree",
  "admin_panel_settings",
  "analytics",
  "apartment",
  "architecture",
  "arrow_back",
  "arrow_forward",
  "auto_stories",
  "bar_chart",
  "block",
  "bolt",
  "brush",
  "chat",
  "check_circle",
  "checklist",
  "close",
  "cloud_done",
  "code",
  "code_blocks",
  "contacts",
  "corporate_fare",
  "dashboard",
  "database",
  "deployed_code",
  "design_services",
  "diamond",
  "dns",
  "draw",
  "edgesys",
  "expand_more",
  "fact_check",
  "gavel",
  "graphic_eq",
  "groups",
  "health_and_safety",
  "history",
  "hub",
  "insights",
  "layers",
  "lock",
  "mail",
  "memory",
  "menu",
  "monitoring",
  "palette",
  "payments",
  "play_circle",
  "psychology",
  "public",
  "query_stats",
  "receipt_long",
  "restaurant",
  "robot_2",
  "rocket_launch",
  "rule",
  "schedule",
  "school",
  "search",
  "security",
  "shield",
  "smart_display",
  "smart_toy",
  "speed",
  "sprint",
  "star",
  "storage",
  "terminal",
  "thermostat",
  "update",
  "verified",
  "verified_user",
  "videocam",
  "visibility",
  "west",
  "work",
];

export const MATERIAL_SYMBOLS_URL = `https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=${USED_ICONS.join(",")}&display=swap`;
